### ISSUE TITLE
[Feature] BucketManager 很多常用方法缺失 ctx 的传递

### ISSUE THREAD

**Issue by shuqingzai** [qiniu/go-sdk#108]
在操作 BucketManager 相关方法时，很多方法没法传递 `context.Context`  ，方法内部直接使用 `context.Background()` ，这很难控制上下文，如：超时，链路追踪等，如何可以设置上下文控制？？

示例：

- https://github.com/qiniu/go-sdk/blob/b4c49d3185d2795d9e186193930eae235e66d4ef/storage/bucket.go#L426
- https://github.com/qiniu/go-sdk/blob/b4c49d3185d2795d9e186193930eae235e66d4ef/storage/bucket.go#L444
- https://github.com/qiniu/go-sdk/blob/b4c49d3185d2795d9e186193930eae235e66d4ef/storage/bucket.go#L456

文件中还有很多。。。

**Comment by bachue** [comment]
确实存在这个问题

**Comment by bachue** [comment]
@shuqingzai 新的版本提供了 storagev2 包，里面的接口都已经接受 `context.Context`。
