### ISSUE TITLE
字节数组上传（表单方式）出现内存泄漏情况，版本：v7.20.1

### ISSUE THREAD

**Issue by guoxk** [qiniu/go-sdk#130]
![WechatIMG631](https://github.com/qiniu/go-sdk/assets/30667416/67ad7929-5dc0-4280-887e-ebad37fd3997)

手动模拟字节数组数据，发现函数结束之后data内存不会被回收，内存会越来越大，手动清空data并gc也不会释放内存，原因应该是Put函数内部的reader没有关闭导致的，请帮我看看怎么回事？

**Comment by guoxk** [comment]
![Uploading WechatIMG631.jpg…]()

**Comment by guoxk** [comment]
![Uploading WechatIMG631.jpg…]()

**Comment by guoxk** [comment]
![Uploading WechatIMG631.jpg…]()

**Comment by guoxk** [comment]
![WechatIMG631](https://github.com/qiniu/go-sdk/assets/30667416/e4064722-d315-4692-bce6-9ecb96323900)

**Comment by bachue** [comment]
@guoxk  建议升级到新的版本，自 v7.21.0 后该问题已经被解决
