### ISSUE TITLE
CallbackURL:      "http://api.example.com/qiniu/upload/callback",   这个怎么填写 ？？

### ISSUE THREAD

**Issue by icetech233** [qiniu/go-sdk#29]
CallbackURL:      "http://api.example.com/qiniu/upload/callback",   这个怎么填写 ？？

api.example.com  这个网址都不存在 ！！

**Comment by bachue** [comment]
填写你这边业务服务器的 URL，你需要确保这个 URL 是可以被从公网访问到的
