### ISSUE TITLE
{"error":"download token auth failed"}

### ISSUE THREAD

**Issue by caowenjundfge** [qiniu/go-sdk#51]
mac := qbox.NewMac(accessKey, secretKey)
domain := "https://image.example.com"  // 域名这块我用的是测试域名
key := "这是一个测试文件.jpg"
deadline := time.Now().Add(time.Second * 3600).Unix() //1小时有效期
privateAccessURL := storage.MakePrivateURL(mac, domain, key, deadline)

这种写法我会有这种错误，要怎么解决

**Comment by bachue** [comment]
这种情况下大概率是 accessKey, secretKey 存在错误

**Comment by xuyunan** [comment]
@caowenjundfge 
1、域名使用自己的绑定的域名，或七牛提供的测试域名
2、域名不可省略http://, 比如 domain = "http://xxx.clouddn.com"

**Comment by caowenjundfge** [comment]
我问客服了，说**私有仓库**要使用自定义域名来测试测试下载，不能使用提供的测试域名

**Comment by caowenjundfge** [comment]
> @caowenjundfge 1、域名使用自己的绑定的域名，或七牛提供的测试域名 2、域名不可省略http://, 比如 domain = "http://xxx.clouddn.com"

@xuyunan
http我加过了
