### ISSUE TITLE
SDK中似乎未包含新的“华东-浙江2”存储区域对应字段？

### ISSUE THREAD

**Issue by miranquil** [qiniu/go-sdk#52]
首先在[开发者中心文档](https://developer.qiniu.com/kodo/1671/region-endpoint-fq)中查到华东-浙江2对应的存储区域 Region ID 为`cn-east-2`。
但使用`storage.GetRegionByID("cn-east-2")`所访问的map并没有这个键值，直接使用`storage.ZoneXXX`也没有找到该区域对应的对象。

**Comment by bachue** [comment]
的确没有 之后会加的

**Comment by miranquil** [comment]
> 的确没有 之后会加的

唔，有没有什么临时应急的解决方案，现在项目想迁移到七牛oss但就买了浙江区域的有点麻烦。

**Comment by bachue** [comment]
其实你不需要指定 region 的，默认情况下 sdk 会使用查询 api 确认 bucket 所在的区域

**Comment by miranquil** [comment]
> 其实你不需要指定 region 的，默认情况下 sdk 会使用查询 api 确认 bucket 所在的区域

😅好嘞，感谢
