### ISSUE TITLE
sdk 抓取网络资源到空间 总是会出现空文件名字

### ISSUE THREAD

**Issue by vasth** [qiniu/go-sdk#55]
使用 bucketManager.FetchWithoutKey 这个方法，很容易出现空文件名字，而且下载后文件无法解析，比如文件类型是pdf，后缀修改pdf后打不开，提示解析失败
会不会空文件名字是还没有下载完成或者是下载一半的问题导致的？

**Comment by YangSen-qn** [comment]
@vasth 能提供下 Fetch 的参数信息吗？我们这边排查下。

**Comment by vasth** [comment]
1、时间比较久了
2、莫名出现的，后来好像又好了
如果最近再出现我在联系你们吧
