### ISSUE TITLE
控制台错误日志 github.com/qiniu/api.v7 is deprecated. And the repository is moved to github.com/qiniu/api.v7 now

### ISSUE THREAD

**Issue by icetech233** [qiniu/go-sdk#64]
控制台错误日志 github.com/qiniu/api.v7 is deprecated. And the repository is moved to github.com/qiniu/api.v7 now

**Comment by bachue** [comment]
按照错误日志里的提示，将 `github.com/qiniu/api.v7` 全部修改成 `github.com/qiniu/api.v7`
