### ISSUE TITLE
 But does not contain package github.com/qiniu/x/xlog.v7

### ISSUE THREAD

**Issue by leo220yuyaodog** [qiniu/go-sdk#66]
![image](https://user-images.githubusercontent.com/71440988/166181219-a84ca12b-2c1d-4341-a4c3-a96820e8c55f.png)
![image](https://user-images.githubusercontent.com/71440988/166181274-5341dcc4-6e8a-4d3b-b7c2-2593409e3710.png)

![image](https://user-images.githubusercontent.com/71440988/166181259-b236edcb-991f-486f-a064-9f098c4117e8.png)
用的是最新的sdk,还是出现无法找到的问题

**Comment by bachue** [comment]
@leo220yuyaodog  你可能需要清理下 `go.sum`？`go mod tidy` 提到的 `github.com/qiniu/api.v7/storage` 已经不可再用了，应该是 `github.com/qiniu/go-sdk/v7/storage`，`auth/qbox` 也是类似的。你可以在目录里 grep 下哪里出现过 `github.com/qiniu/api.v7` 这个字样。
