### ISSUE TITLE
上传进度如何计算百分比？

### ISSUE THREAD

**Issue by hessonsu** [qiniu/go-sdk#68]
上传进度如何计算百分比？
nofify = func(partNumber int64, ret *storage.UploadPartsRet) {}
partNumber 这个应该是上传的分片编号。
我还需要自己计算分片总数？似乎分片总数由SDK给我更好吧？

**Comment by YangSen-qn** [comment]
@hessonsu 
已上传的文件大小 = 上传分片数 x 分片大小

以此方式获取上传的文件大小，然后再计算上传进度。
