### ISSUE TITLE
没有智能多媒体服务回调请求校验的相关方法

### ISSUE THREAD

**Issue by tryte000** [qiniu/go-sdk#73]
没有找到哪里有针对智能多媒体服务任务完成后回调请求的数据校验方法

**Comment by bachue** [comment]
之后将添加这部分支持

**Comment by tryte000** [comment]
没有这部分支持那能否先在API文档中进行token校验的说明？不得不说，关于token这部分文档中写得很模糊，什么时候用什么前缀，如何校验等等都十分不清晰，这种情况下不依赖SDK自己实现的话复杂度激增

**Comment by YangSen-qn** [comment]
感谢您的反馈
