### ISSUE TITLE
删除文件时错误类型不一致

### ISSUE THREAD

**Issue by mesfreeman** [qiniu/go-sdk#98]
当删除的文件不存在时，实际的报错类型与SDK中声明的[错误类型](https://github.com/qiniu/go-sdk/blob/7e1124f454d66d2bec2e9fa56b07f5df7c4c28b5/storage/errs.go#LL12C35-L12C35)不一致

* 实际的报错类型为 `No such file or directory`
* SDK中声明的错误为 `no such file or directory`

文本内容大小写不一致，因此导致无法使用 `errors.Is(err, storage.ErrNoSuchFile)` 进行异常判断，请及时修复，谢谢～

**Comment by bachue** [comment]
好的，我们看下

**Comment by YangSen-qn** [comment]
@mesfreeman 请参考如下逻辑进行判断：
```
	if err == nil {
		return
	}

	errInfo, ok := err.(*client.ErrorInfo)
	if !ok {
		return
	}
	
	if errInfo.Code == 612 {
		// 资源不存在
	}
```

**Comment by mesfreeman** [comment]
@YangSen-qn 了解了，看了下你们的测试用例，原来你们是推荐用状态码来判断 😅
